### PR TITLE
Odometer enhancements

### PR DESCRIPTION
**Pull request by vvUnai**
- Performance-related edit: refactored getDialPosition method (from floating point to integer arithmetic) for a 20-fold reduction in CPU utilization.
- Added capability of setting (w/animation) the odometer to a specified value, in addition to the classic increment-by-one behavior.
- Added some javadocs.
- Used diamond inference where applicable (version 2.2-r5+ has jre7 as a requirement).

### CODE REVIEW

**Comment by vvUnai** [comment]
Hi everyone,
is Gerrit still active here on github? I see that he hasn't had any activity since September, unlike his very prolific previous months. I hope all is well!
I also read that gauges are being [temporarily?] removed from the 8.0 branch, but not from the 2.2.
If there is nobody in place already, I would like to be a maintainer of such code in the 2.2 branch, applying bugfixes, performance tweaks, or minor changes like that.

**Comment by jeffreyguenther** [comment]
It is my understanding Gerrit moved his guages to a separate repo: https://bitbucket.org/hansolo/enzo/wiki/Home

**Comment by tbee** [comment]
Correct. This is because it wanted total freedom to write his stuff for the demo's he is making. You can use them, but there is guarentee until the exit (as we call it). The idea is that I'll be picking up his stuff and moving them to JFXtras for a more formal release. But time is a problem.

Tom

**Comment by vvUnai** [comment]
Can't these commits be merged anyway (transitionally) for the "exiting" jfxtras 2.2? They're very useful - until we get Gerrit's feedback for the 8.0 version

**Pull request merged**
