### PR TITLE
Adding continuous integration using travis-ci.org

### PR DESCRIPTION
**Pull request by McFoggy**
Addition of .travis.yml in order to integrate travis-ci infrastructure.
What would be required then would be to link a travis account to the Github JFXtras/jfxtras-labs repository. This must be done by a member of the JFXtras community github project because right access is required so that Travis can register a pull hook. I would be able to do it I think if someone could add me to the JFXtras github community.

The build from travis is correctly working as shown on the ci-build of my fork : https://travis-ci.org/McFoggy/jfxtras-labs

Next step would be then to add automatic snapshot deployment, but it is another story.

### CODE REVIEW

**Comment by tbee** [comment]
Hm. Does it really run the one UI test that is included?

> Building > :compileTestJava > :processTestResources> Building > :testClasses> Building > :test > Resolving dependencies ':testRuntime' > 1 test completed> Building > :test > 1 test completedissing on display ":99.0".

Both Jenkins environments that are currently configured do not.

Tom

**Comment by McFoggy** [comment]
Hi Tom,

I did not checked how much UI tests are expected to run but I guess that at least one UI test exists in the project as the [first build](https://travis-ci.org/McFoggy/jfxtras-labs/builds/11503736) was failing.

I'll have a deeper look and compare build results from my machine and travis-ci.

Matthieu

**Comment by tbee** [comment]
It would be great to have a build that actually tests the UI. Now there is only one, but more are to be expected.

If not, what would be the advantage of building via Travis instead of Jenkins?

Tom

**Comment by McFoggy** [comment]
Tom,

I enhanced the travis.yml file (only in my fork at the moment) so that the build output is more friendly:
- using a console compliant TERM variable
- adding some --info to gradle command
- outputing tests result to console

Result is as follow

``` xml
<!-- 
    From TRAVIS-CI : build\test-results\TEST-jfxtras.labs.scene.control.test.ListSpinnerTest1.xml 
    see build: https://travis-ci.org/McFoggy/jfxtras-labs/builds/11511704
-->
<testsuite name="jfxtras.labs.scene.control.test.ListSpinnerTest1" tests="1" failures="0" errors="0" timestamp="1970-01-01T00:00:00" hostname="testing-worker-linux-6-2-11850-linux-2" time="1.379515547465E9">
  <properties/>
  <testcase name="select" classname="jfxtras.labs.scene.control.test.ListSpinnerTest1" time="6.398"/>
  <system-out><![CDATA[Loading jemmy properties from /home/travis/.jemmy.properties
Property file /home/travis/.jemmy.properties does not exists. Ignoring.
Input factory set to org.jemmy.input.AWTRobotInputFactory[otherVM=false, mouseSmoothness=2147483647, keyMap=org.jemmy.input.AWTMap@16f64454]
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>

<!-- From MY_COMPUTER : build\test-results\TEST-jfxtras.labs.scene.control.test.ListSpinnerTest1.xml -->

<?xml version="1.1" encoding="UTF-8"?>
<testsuite name="jfxtras.labs.scene.control.test.ListSpinnerTest1" tests="1" failures="0" errors="0" timestamp="1970-01-01T00:00:00" hostname="xxxxxxxxxxx" time="1.379514761609E9">
  <properties/>
  <testcase name="select" classname="jfxtras.labs.scene.control.test.ListSpinnerTest1" time="1.766"/>
  <system-out><![CDATA[Loading jemmy properties from D:\Users\awxgx\.jemmy.properties
Property file D:\Users\awxgx\.jemmy.properties does not exists. Ignoring.
Input factory set to org.jemmy.input.AWTRobotInputFactory[otherVM=false, mouseSmoothness=2147483647, keyMap=org.jemmy.input.AWTMap@1b8aa1a]
]]></system-out>
  <system-err><![CDATA[WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-shadow-highlight-color' while resolving lookups for '-fx-background-color' from rule '*.text-field' in stylesheet jar:file:/D:/dev/tools/orbis/java/1.7.0_21-AP-3.0.0/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-text-inner-color' while resolving lookups for '-fx-text-fill' from rule '*.text-field' in stylesheet jar:file:/D:/dev/tools/orbis/java/1.7.0_21-AP-3.0.0/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-control-inner-background' while resolving lookups for '-fx-prompt-text-fill' from rule '*.text-field' in stylesheet jar:file:/D:/dev/tools/orbis/java/1.7.0_21-AP-3.0.0/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-accent' while resolving lookups for '-fx-highlight-fill' from rule '*.text-input' in stylesheet jar:file:/D:/dev/tools/orbis/java/1.7.0_21-AP-3.0.0/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-mark-color' while resolving lookups for '-fx-background-color' from rule '*.ListSpinner *.idle' in stylesheet file:/D:/dev/projects/os/JavaFX/jfxtras-labs-McFoggy/build/resources/main/jfxtras/labs/internal/scene/control/ListSpinner.css
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-mark-color' while resolving lookups for '-fx-background-color' from rule '*.ListSpinner *.idle' in stylesheet file:/D:/dev/projects/os/JavaFX/jfxtras-labs-McFoggy/build/resources/main/jfxtras/labs/internal/scene/control/ListSpinner.css
]]></system-err>
</testsuite>
```

So except that system-err output is different (probably because of output redirection of travis jobs) we have the same result for the GUI test using Jemmy.

I also pushed a failing test (in the Jemmy test) to a branch in my fork and it is failing as expected, see [build 5](https://travis-ci.org/McFoggy/jfxtras-labs/builds/11513066).
I am going to amend the pull request to enhance the travis.yml build with latest enhancements (console TERM, --info parameter, show errors in console only on failure)

Matthieu

**Comment by McFoggy** [comment]
Tom,

just to add some arguments and answer your previous question, I would say that the travis build:
- allows the Jemmy UI tests to be performed
- offers a free cloud infrastructure for CI
- does not disturb more than the .travis.yml file
- allow to put build badges on the project page
- can give more visibility to the CI infrastructure & build result of the project
- integrates seemlessly with github workflows (see the build result paragraph in green added by travis to this pull request)

**Comment by tbee** [comment]
The fact that travis is actually running the UI test is a big gain. When you've added the chance, I'll merge the pull request. Do you prefer developer rights on the project?

BTw, any chance Travis also has JDK8ea available?

Tom

**Comment by McFoggy** [comment]
_> When you've added the chance, I'll merge the pull request._
Sorry what do you expect? The GUI tests are performed currently by the travis build (see build 5 where I intentionnaly introduced a test failure to demonstrate it).

_> Do you prefer developer rights on the project?_
I'd prefer because seting up the travis integration would require a 'commit' right on the project (in order to add the pull hook)

_> BTw, any chance Travis also has JDK8ea available?_
I'll dig the docs and email the guys to have some feedback on this.

Thanks.

**Comment by tbee** [comment]
On 2013-09-19 10:50, Matthieu Brouillard wrote:

> /> When you've added the chance, I'll merge the pull request./
> Sorry what do you expect? The GUI tests are performed currently by the travis build (see build 5 where I intentionnaly introduced a test failure to demonstrate it).

Sorry, I thought you would "update the travis.yml" which is part of a pull request. So that would mean you expect me to merge it.

> /> Do you prefer developer rights on the project?/
> I'd prefer because seting up the travis integration would require a 'commit' right on the project (in order to add the pull hook)

Ok, I'll set you up with that ASAP, you'll need to sign a waiver (as all committers have done).

> /> BTw, any chance Travis also has JDK8ea available?/
> I'll dig the docs and email the guys to have some feedback on this.

Great!

**Comment by McFoggy** [comment]
Tom,

If you merge the pull request you'll benefit from the latest version of the travis.yml file.

_> sign a waiver_
I'll contact you directly by email to have more details.

**Pull request merged**
