### PR TITLE
Update SplitFlapSkin.java

### PR DESCRIPTION
**Pull request by vvUnai**
Fix for issue #19.

### CODE REVIEW

**Comment by HanSolo** [comment]
Modifications added in the process of porting the controls to JavaFX 8. Please find the updated version in the Master 8.0 branch.

**Comment by vvUnai** [comment]
Ok, thank you.
Will the 8.0 branch be backwards compatible with Java 7, or shall I maintain my separate 2.2 branch with the patched SplitFlat?
Please forgive me if question is stupid, but I'm very new at GitHub and its mechanics (and JavaFX altogether, for that matter)

**Comment by tbee** [comment]
JFXtras 8.0 is not compatible with JavaFX 2.2. And since J7 comes with JFX2.2, and J8 with JFX8, the answer is 'no'. You would need to maintain your own copy or Gerrit must apply the patch to the JFXtras 2.2 branch as well.

**Comment by HanSolo** [comment]
Nope, the 8.0 branch is not backwards compatible due to changes in JavaFX 8 controls. Have to find some more time to patch also the 2.2 version or you could also use your patched version...

Cheers,

Gerrit

Am 29.03.2013 um 09:09 schrieb Unai notifications@github.com:

**Pull request closed without merging**
