### PR TITLE
Improved FXML compatibility in the Window component

### PR DESCRIPTION
**Pull request by laxika**
Improved FXML compatibility in the Window component

### CODE REVIEW

**Comment by miho** [comment]
FXML compatibility is great. Out of curiosity: for what purpose do you use the Window control?

**Comment by laxika** [comment]
I'm writing a trading card game right now. Actually using it to show a small game room creating menu on the game searching panel. (Players can give a name to the room, choose game type etc...) The window is centered, non-resizable and non-movable. :) I'll use the Window controll for a lot of stuff later.

Edit:

And also using it on the game room joining, showing a small window where the player can choose his/her deck for the match.

**Comment by miho** [comment]
Nice! Is the game open source?

**Comment by laxika** [comment]
No, i don't plan it to be open source. It'll be online, with a JFX client and a Netty server. I plan it to be a "professional" game. Fortunately I have a friend who is studying in a graphics school, and he will do the graphics for me. This will be our first big game. :)

By the way if I develop something cool (eg. a new control) or improve something on the existing controlls, I'll push them here to help the community too.

**Pull request merged**
