### PR TITLE
Code cleanup and Window control enchantments

### PR DESCRIPTION
**Pull request by laxika**
Removed some unused calculations/variables from the Window control.
Added setResizable and setMovable functions to the Window control.

### CODE REVIEW

**Comment by tbee** [comment]
The additions seem like a good idea. 
The some off the stuff that got cleaned up look to me like placeholders that actually need implementation (e.g. // update item). So this commit is two fold to me; part is ok, part I'm in doubt about.

Merging this pull request (or not) is the responsibility of the owner of this code (being Michael Hoffer).

**Comment by laxika** [comment]
Sorry, pushing it up in two commit would be a better idea, but I not planned to push this up, only planned to use it in my game, but then I realised it can be usefull for others, but that was too late, I removed a lot placeholders. They seemed unnecessary at that time.

**Comment by tbee** [comment]
No problem. It is great that you contribute in the first place, just reviewing the pull request as I would any.

Tom

**Comment by miho** [comment]
I'll add the resizable/movable additions. That's really useful.
I will rename the `setResizable()` to `setResizableWindow()` etc. to be consistent.

I won't merge all the cleanup code. In a lab-project it is not wise to remove all unused variables/code ;)

Thanks for the contribution! 

Michael

**Comment by miho** [comment]
Features are added. Thanks again! 

Michael

**Pull request closed without merging**
